- name: Configure HAProxy on ha-std-postgress node
  hosts: ha_proxy
  become: true
  gather_facts: true

  tasks:
    - name: Gather facts for all pg_nodes
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['pg_nodes'] }}"

    - name: Initialize pg_nodes
      set_fact:
        pg_nodes: []

    - name: Get PostgreSQL node IP addresses
      set_fact:
        pg_nodes: "{{ pg_nodes + [{'fqdn': hostvars[item]['ansible_fqdn'] if hostvars[item]['ansible_fqdn'] is defined else item, 'ip': hostvars[item]['ansible_default_ipv4']['address'] if hostvars[item]['ansible_default_ipv4'] is defined else 'unknown'}] }}"
      loop: "{{ groups['pg_nodes'] }}"

    - name: Debug pg_nodes type and content
      debug:
        msg: "pg_nodes: {{ pg_nodes }} | Type: {{ pg_nodes | type_debug }}"

    - name: Check if HAProxy configuration file exists
      stat:
        path: /etc/haproxy/haproxy.cfg
      register: haproxy_cfg

    - name: Back up the existing HAProxy configuration file
      command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
      when: haproxy_cfg.stat.exists
      ignore_errors: yes

    - name: Configure HAProxy
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          global
              maxconn 100

          defaults
              log global
              mode tcp
              retries 2
              timeout client 30m
              timeout connect 4s
              timeout server 30m
              timeout check 5s

          listen stats
              mode http
              bind *:7000
              stats enable
              stats uri /

          listen primary
              bind *:5000
              option httpchk /primary
              http-check expect status 200
              default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
              {% for node in pg_nodes %}
              server {{ node.fqdn }} {{ node.ip }}:5432 maxconn 100 check port 8008
              {% endfor %}

          listen standbys
              balance roundrobin
              bind *:5001
              option httpchk /replica
              http-check expect status 200
              default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
              {% for node in pg_nodes %}
              server {{ node.fqdn }} {{ node.ip }}:5432 maxconn 100 check port 8008
              {% endfor %}
        create: yes

    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
